name: Terraform CI/CD
on:
  workflow_dispatch:
    inputs:
        plan:
          description: 'Gostaria de aplicar o Plan?'
          required: true
          type: choice
          options:
            - true
            - false

        apply:
          description: 'Gostaria de aplicar o Apply?'
          required: true
          type: choice
          options:
            - true
            - false

        destroy:
          description: 'Gostaria de aplicar o destroy?'
          required: true
          type: choice
          options:
            - true
            - false

permissions:
  id-token: write

jobs:
  init_and_credentials:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6.0.0
      with:
        role-to-assume: arn:aws:iam::165518479712:role/git-actions-role
        aws-region: us-east-2

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v4.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform fmt
      run: terraform fmt

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform plan
      run: terraform plan
      if: github.event.inputs.plan == 'true'

    - name: Terraform apply
      run: terraform apply -auto-approve
      if: github.event.inputs.apply == 'true'

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      if: github.event.inputs.destroy == 'true'
